### ISSUE TITLE
ReferenceError: ClassyTestCase is not defined

### ISSUE THREAD

**Issue by brianlukoff** [peerlibrary/meteor-related#10]
Since upgrading from 0.1.9 to 0.2.0, I'm getting `ReferenceError: ClassyTestCase is not defined` on startup. I don't get the same error when running from my updated-for-Meteor-1.8.1 fork of 0.1.9 -- is it possible that some of the upgraded packages in 0.2.0 made a difference?

**Comment by mitar** [comment]
I will assume this is the problem of: https://github.com/meteor/meteor/issues/8512

**Comment by mitar** [comment]
Try 0.2.1.

**Comment by mitar** [comment]
Or not. :-( CI is failing.

I am not really using/maintaining this package anymore, in favor of reactive publish. If you want, I could give you mainternership over it.

What you probably want to do if you are using it in Meteor 1.8.1 is to port it to CoffeeScript 2 (probably not much changes needed, only dependencies) and publish it.

So it seems the problem is that it is an old package and some Meteor dependencies do not work well anymore so it would have to all be bumped to a newer version.

**Comment by brianlukoff** [comment]
Sure - I can try to fix. Happy to commit directly, or I can try to make a PR.

**Comment by mitar** [comment]
I think it is one of those things which you have to publish a package before you can see if it works. It is really a problem with Meteor packaging. I will add you to the repo and Meteor package. So that you can both push to the repo and publish a package and good luck. :-)

What is your username in Meteor ecosystem?

**Comment by brianlukoff** [comment]
OK -- thanks! I'm `brianlukoff`.

**Comment by mitar** [comment]
Added to both.
